# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: video_stream.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='video_stream.proto',
  package='doorlock_sniper',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12video_stream.proto\x12\x0f\x64oorlock_sniper\"\x1f\n\x0f\x43ustomByteBlock\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x62\x06proto3'
)




_CUSTOMBYTEBLOCK = _descriptor.Descriptor(
  name='CustomByteBlock',
  full_name='doorlock_sniper.CustomByteBlock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='doorlock_sniper.CustomByteBlock.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=70,
)

DESCRIPTOR.message_types_by_name['CustomByteBlock'] = _CUSTOMBYTEBLOCK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CustomByteBlock = _reflection.GeneratedProtocolMessageType('CustomByteBlock', (_message.Message,), {
  'DESCRIPTOR' : _CUSTOMBYTEBLOCK,
  '__module__' : 'video_stream_pb2'
  # @@protoc_insertion_point(class_scope:doorlock_sniper.CustomByteBlock)
  })
_sym_db.RegisterMessage(CustomByteBlock)


# @@protoc_insertion_point(module_scope)
