# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: video_stream.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='video_stream.proto',
  package='doorlock_sniper',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12video_stream.proto\x12\x0f\x64oorlock_sniper\"\x1f\n\x0f\x43ustomByteBlock\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\xc2\x01\n\nGameStatus\x12\x15\n\rcurrent_round\x18\x01 \x01(\r\x12\x14\n\x0ctotal_rounds\x18\x02 \x01(\r\x12\x11\n\tred_score\x18\x03 \x01(\r\x12\x12\n\nblue_score\x18\x04 \x01(\r\x12\x15\n\rcurrent_stage\x18\x05 \x01(\r\x12\x1b\n\x13stage_countdown_sec\x18\x06 \x01(\x05\x12\x19\n\x11stage_elapsed_sec\x18\x07 \x01(\x05\x12\x11\n\tis_paused\x18\x08 \x01(\x08\x62\x06proto3'
)




_CUSTOMBYTEBLOCK = _descriptor.Descriptor(
  name='CustomByteBlock',
  full_name='doorlock_sniper.CustomByteBlock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='doorlock_sniper.CustomByteBlock.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=70,
)


_GAMESTATUS = _descriptor.Descriptor(
  name='GameStatus',
  full_name='doorlock_sniper.GameStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='current_round', full_name='doorlock_sniper.GameStatus.current_round', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_rounds', full_name='doorlock_sniper.GameStatus.total_rounds', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='red_score', full_name='doorlock_sniper.GameStatus.red_score', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='blue_score', full_name='doorlock_sniper.GameStatus.blue_score', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='current_stage', full_name='doorlock_sniper.GameStatus.current_stage', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stage_countdown_sec', full_name='doorlock_sniper.GameStatus.stage_countdown_sec', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stage_elapsed_sec', full_name='doorlock_sniper.GameStatus.stage_elapsed_sec', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_paused', full_name='doorlock_sniper.GameStatus.is_paused', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=267,
)

DESCRIPTOR.message_types_by_name['CustomByteBlock'] = _CUSTOMBYTEBLOCK
DESCRIPTOR.message_types_by_name['GameStatus'] = _GAMESTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CustomByteBlock = _reflection.GeneratedProtocolMessageType('CustomByteBlock', (_message.Message,), {
  'DESCRIPTOR' : _CUSTOMBYTEBLOCK,
  '__module__' : 'video_stream_pb2'
  # @@protoc_insertion_point(class_scope:doorlock_sniper.CustomByteBlock)
  })
_sym_db.RegisterMessage(CustomByteBlock)

GameStatus = _reflection.GeneratedProtocolMessageType('GameStatus', (_message.Message,), {
  'DESCRIPTOR' : _GAMESTATUS,
  '__module__' : 'video_stream_pb2'
  # @@protoc_insertion_point(class_scope:doorlock_sniper.GameStatus)
  })
_sym_db.RegisterMessage(GameStatus)


# @@protoc_insertion_point(module_scope)
